version: '3'

services:
  setswana-marker:
    build: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    network_mode: "host"  # Required for GUI applications